### ISSUE TITLE
Class uses module, that uses another module

### ISSUE THREAD

**Issue by vitalexbel** [peq/WurstScript#542] opened 2017-07-03 12:03 UTC
Its a question.
When I use LinkedListModule, its OK:
```
class MyClass
	use LinkedListModule
```
but when I use another module, that use LinkedListModule without any additional functions, members etc...
```
class MyClass
	use AnotherModule
	
public module AnotherModule
	use LinkedListModule
```
I get an error:
```
2017-07-03 14:46:48 INFO   progress: Translating wurst. Phase 1: to intermediate lang
2017-07-03 14:46:48 INFO   translating program to jass ... 
2017-07-03 14:46:48 INFO   progress: Translating wurst. Phase 2: translate classes
2017-07-03 14:46:48 SEVERE Error
java.lang.IllegalArgumentException: Element func must not be null.
	at de.peeeq.wurstscript.jassIm.ImFunctionCallImpl.<init>(ImFunctionCallImpl.java:10)
	at de.peeeq.wurstscript.jassIm.JassIm.ImFunctionCall(JassIm.java:112)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateClasses.replaceMethodCall(EliminateClasses.java:397)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateClasses.eliminateClassRelatedExprs(EliminateClasses.java:283)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateClasses.eliminateClasses(EliminateClasses.java:39)
	at de.peeeq.wurstio.WurstCompilerJassImpl.transformProgToJass(WurstCompilerJassImpl.java:341)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:274)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:93)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:26)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$30(LanguageWorker.java:176)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:151)
	at java.lang.Thread.run(Unknown Source)
```
I dont understand why.
Module cannot pass functionality through another module to my class or what?
Can you explain me cause of this behaviour?
Thx for help in advance

**Comment by vitalexbel** [comment] 2017-07-03 12:09
> NOTE: It is likely that the concept of modules will change in later versions of the language. If you want to be on the safe side you should not create modules which use other modules themselves. Plain, flat modules will most likely stay in the language.
I read about this in the Manual.
Will the use of modules inside other modules be possible in the future?

**Comment by Frotty** [comment] 2017-07-03 12:15
The code you pasted above works fine. The error must be caused by something else.

Show the code of the module and class

**Comment by vitalexbel** [comment] 2017-07-03 12:32
Yes you are right.
I found the error. 
1: (It's OK)
```
package MyClass
import NewModule

public class MyClass
	use NewModule
	
package NewModule
import LinkedListModule

public module NewModule
	use LinkedListModule
```
2) Error:
```
package MyClass
import NewModule
import LinkedListModule

public class MyClass
	use NewModule
	
package NewModule
import LinkedListModule

public module NewModule
	use LinkedListModule
```
I realized that when I import LinkedListModule package into MyClass (the only difference between two codes above), I get an error.

**Comment by Frotty** [comment] 2017-07-03 12:47
The second paste does not throw an error for me either.

**Comment by vitalexbel** [comment] 2017-07-03 14:52
I received an error again.
when a class has static function with iteration it gives an error:
```
// MyClass.wurst
package MyClass
import MyModule

public class MyClass
	use NewModule

	static function all()
		for elem in MyClass
			elem.do()

	function do()
		// do something

// MyModule.wurst
package MyModule
import LinkedListModule

public module MyModule
	use LinkedListModule
```

**Comment by peq** [comment] 2017-07-03 18:32
Thanks for the small example!

It should be fixed now, repoen if there are still problems.

**Comment by vitalexbel** [comment] 2017-07-03 20:50
now I get
```
2017-07-03 23:49:28 INFO   progress: Translating wurst. Phase 1: to intermediate lang
2017-07-03 23:49:28 INFO   translating program to jass ... 
2017-07-03 23:49:28 INFO   progress: Translating wurst. Phase 2: translate classes
2017-07-03 23:49:28 SEVERE Error
java.lang.RuntimeException: java.nio.file.NoSuchFileException: test-output\before-classes.im
	at de.peeeq.wurstscript.translation.imtranslation.EliminateClasses.eliminateClasses(EliminateClasses.java:42)
	at de.peeeq.wurstio.WurstCompilerJassImpl.transformProgToJass(WurstCompilerJassImpl.java:341)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:274)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:93)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:26)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$30(LanguageWorker.java:176)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:151)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.NoSuchFileException: test-output\before-classes.im
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.nio.file.Files.newOutputStream(Unknown Source)
	at java.nio.file.Files.write(Unknown Source)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateClasses.eliminateClasses(EliminateClasses.java:40)
	... 7 more
```

**Comment by Frotty** [comment] 2017-07-03 23:52
you must update the wurst 4 vscode plugin

**Comment by vitalexbel** [comment] 2017-07-04 09:16
Updated, but it did not help.

**Comment by vitalexbel** [comment] 2017-07-04 09:24
When I try to run any map, I get this error now.
even the map with only 1 package without any code etc.

**Comment by Frotty** [comment] 2017-07-04 09:28
Yea @peq constantly forgets differencesd between windows and unix

**Comment by vitalexbel** [comment] 2017-07-04 10:43
```
package TestModule

import LinkedListModule

public module TestModule
    use LinkedListModule
```
```
package Test

import TestModule
import Wurstunit

class TestClass
    static string s
    use TestModule

    construct()
        s+= "@"

    static function allTests()
        for testClass in TestClass
            testClass.do()
            
    function do()
        s+= "!"

    static function reset()
        s = ""
@test
function test()
    TestClass.reset()
    let a = new TestClass
    let b = new TestClass
    TestClass.s.assertEquals("@@")
    a.do()
    b.do()
    TestClass.s.assertEquals("@@!!")

@test
function test2()
    TestClass.reset()
    new TestClass
    new TestClass
    TestClass.allTests()
    TestClass.s.assertEquals("@@!!")
```
I get test fail:
```
Running tests ... 



Testing function test (C:\Games\Wurst\Projects\new\wurst\Test.wurst, line 29)	...

?

Testing function test2 (C:\Games\Wurst\Projects\new\wurst\Test.wurst, line 39)	...

FAIL

1 tests OK, 
1 tests failed

function test2 (C:\Games\Wurst\Projects\new\wurst\Test.wurst, line 39)
	test failed: expected @@!! but was @@
	at function call testFail() (C:\Games\Wurst\Libraries\wurstStdlib2\_wurst\Wurstunit.wurst, line 29)
```

**Comment by vitalexbel** [comment] 2017-07-04 11:08
```
package Test

import TestModule
import Wurstunit

init
    let t = CreateTimer()
    t.start(0.5,() -> begin
        new TestClass
        new TestClass
        TestClass.allTests()
        print("test [" + TestClass.s + "]")
    end)

class TestClass
    static string s
    use TestModule

    construct()
        s+= "@"

    static function allTests()
        for testClass in TestClass
            testClass.do()
            
    function do()
        s+= "!"

    static function reset()
        s = ""
@test
function test()
    TestClass.reset()
    testPrint("size: " + TestClass.size.toString())
    let a = new TestClass
    let b = new TestClass
    testPrint("size: " + TestClass.size.toString())
    TestClass.s.assertEquals("@@")
    a.do()
    b.do()
    TestClass.s.assertEquals("@@!!")
    for testClass in TestClass
        destroy testClass

@test
function test2()
    TestClass.reset()
    testPrint("size: " + TestClass.size.toString())
    new TestClass
    new TestClass
    testPrint("size: " + TestClass.size.toString())
    TestClass.allTests()
    TestClass.s.assertEquals("@@!!")
    for testClass in TestClass
        destroy testClass
```
```
package TestModule

import LinkedListModule

public module TestModule
    use LinkedListModule
```
Tests:
```
Running tests ... 
Testing function test (C:\Games\Wurst\Projects\new\wurst\Test.wurst, line 31)	...
size: 0
size: 0
?

Testing function test2 (C:\Games\Wurst\Projects\new\wurst\Test.wurst, line 45)	...
size: 0
size: 0
FAIL

1 tests OK, 
1 tests failed

function test2 (C:\Games\Wurst\Projects\new\wurst\Test.wurst, line 45)
	test failed: expected @@!! but was @@
	at function call testFail() (C:\Games\Wurst\Libraries\wurstStdlib2\_wurst\Wurstunit.wurst, line 29)
```

**Comment by vitalexbel** [comment] 2017-07-04 13:48
I found the code section where the class is created.
When use TestModule that use LinkedListModule:
```
function construct_TestClass takes integer this returns nothing
	set TestClass_s = TestClass_s + "@"
endfunction

function new_TestClass takes nothing returns integer
	local integer this = alloc_TestClass()
	call construct_TestClass(this)
	return this
endfunction
```

When use LinkedListModule:
```
function construct_TestClass_LinkedListModule takes integer this returns nothing
	set LinkedListModule_size = LinkedListModule_size + 1
	if LinkedListModule_size == 1 then
		set LinkedListModule_first = this
	else
		set LinkedListModule_next[LinkedListModule_last] = this
	endif
	set LinkedListModule_next[this] = 0
	set LinkedListModule_last = this
endfunction

function construct_TestClass takes integer this returns nothing
	call construct_TestClass_LinkedListModule(this)
	set TestClass_s = TestClass_s + "@"
endfunction

function new_TestClass takes nothing returns integer
	local integer this = alloc_TestClass()
	call construct_TestClass(this)
	return this
endfunction
```

**Comment by peq** [comment] 2017-07-04 19:28
The problem with constructor-calls should be fixed with commit 8e9dfd4d8689e2a01a5f677a97bc0d69383c2fe7

Can you try if it works now?

**Comment by vitalexbel** [comment] 2017-07-04 23:28
tested. everything works fine now (at least, my previous tests)

**Comment by vitalexbel** [comment] 2017-07-05 09:04
found 1 problem with static class in module that extends abstract class and **override abstract function**
for example. this code works fine:
```
package TestModule
import LinkedListModule

abstract class TestClass_2
    int i
    construct(int i)
        this.i = i
    
    // abstract function dodo()

public module TestModule
    static string moduleString = ""
    use LinkedListModule

    construct()
        moduleString += "*"

    static function doStatic()
        print("static func in module")
        new ClassInModule(first)

    static class ClassInModule extends TestClass_2
        TestModule.thistype first

        construct(TestModule.thistype first)
            super(5)
            this.first = first
```
but this gives an error:
```
package TestModule

import LinkedListModule

abstract class TestClass_2
    int i
    construct(int i)
        this.i = i
    
    abstract function dodo()

public module TestModule
    static string moduleString = ""
    use LinkedListModule

    construct()
        moduleString += "*"

    static function doStatic()
        print("static func in module")
        new ClassInModule(first)

    static class ClassInModule extends TestClass_2
        TestModule.thistype first

        construct(TestModule.thistype first)
            super(5)
            this.first = first

        override function dodo()
            first = null
```
The only difference is **override function dodo()**
Log:
```
2017-07-05 12:02:24 INFO   translating program ... 
2017-07-05 12:02:24 INFO   progress: Translating wurst. Phase 1: to intermediate lang
2017-07-05 12:02:24 INFO   translating program to jass ... 
2017-07-05 12:02:24 INFO   progress: Translating wurst. Phase 2: translate classes
2017-07-05 12:02:25 SEVERE Error
java.lang.NullPointerException
	at de.peeeq.wurstscript.translation.imtojass.ImAttributes.attrClass(ImAttributes.java:100)
	at de.peeeq.wurstscript.jassIm.ImMethodImpl.attrClass(ImMethodImpl.java:152)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateClasses.calculateTypeIdToMethodHelper(EliminateClasses.java:224)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateClasses.calculateTypeIdRanges(EliminateClasses.java:194)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateClasses.createDispatchFunc(EliminateClasses.java:71)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateClasses.eliminateClass(EliminateClasses.java:58)
	at de.peeeq.wurstscript.translation.imtranslation.EliminateClasses.eliminateClasses(EliminateClasses.java:38)
	at de.peeeq.wurstio.WurstCompilerJassImpl.transformProgToJass(WurstCompilerJassImpl.java:341)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:274)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:93)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:26)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$30(LanguageWorker.java:176)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:151)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by vitalexbel** [comment] 2017-07-05 23:28
everything works now
```
package TestModule
import LinkedListModule

class TestClass
    static string s
    use TestModule
    construct()
        s+= "@"
    static function allTests()
        for testClass in TestClass
            testClass.do()      
    function do()
        s+= "!"

abstract class AbstractClass
    int i
    construct(int i)
        this.i = i
        dodo()
    abstract function dodo()

public module TestModule
    use LinkedListModule
    static string moduleString = ""
    construct()
        moduleString += "%"

    static function doStatic()
        let temp = new ClassInModule()
        moduleString += temp.i.toString()

    static class ClassInModule extends AbstractClass
        construct()
            super(5)
        override function dodo()
            i+= 1

init
    let t = CreateTimer()
    t.start(0.5,() -> begin
        new TestClass
        new TestClass
        TestClass.allTests()
        TestClass.doStatic()
        print("test [" + TestClass.s + TestClass.moduleString + "]")
    end)
```
![screenshot_1](https://user-images.githubusercontent.com/29229748/27889024-4b5753cc-61f2-11e7-97fa-5bdc489abe3e.png)
1) using module that use another module (with unique constructors)
2) static class in module that extends abstract class with override funcs.

its cool 👍

**Closed** 2017-07-18 12:30 UTC
